Lint track config practice exercise practices prerequisites
exercism/configlet pull request #421
Opened 2021-09-08 13:09 UTC by ee7

This PR will be just for the final two commits.

---

At the time of writing, this PR produces [this diff](https://gist.github.com/ee7/d7b3b2c1ba0db95a299eee3fd472604e) to the output of `configlet lint`, per track.

The diff is very large - bigger than the maximum length of a GitHub PR. What do we want to do?

2021-09-08 13:46 UTC, ErikSchierboom approved these changes
👍

2021-09-08 13:55 UTC, ee7 commented
@ErikSchierboom Did you see the large diff to the output of `configlet lint`? Do we want to temporarily disable any of these rules, or merge as-is?

2021-09-08 14:00 UTC, ErikSchierboom commented
@ee7 Let me think on that for a bit

2021-09-08 14:10 UTC, ErikSchierboom commented
@ee7 We've consider this for a bit, and what we'd prefer is for the practices/prerequisites checks to become warnings (as in: not fail linting). Our reasons for this are:

1. There's been quite a bit of work in getting the practices filled in, and we wouldn't want tracks to lose that work to satisfy configlet
2. It might overwhelm maintainers a bit, which might be a bad thing to do at this point of time with v3 just being released and maintainers already having to deal with many changes

That said, I _do_ want this to be enabled at some point. Maybe we can:

1. Still show the error messages for missing practices/prerequisites concepts
2. Add a warning somewhere in the output that at some point (end of October?) we will make these warnings an error
3. Don't register them as actual errors (do not fail the build)

2021-09-08 14:11 UTC, ErikSchierboom requested changes
See https://github.com/exercism/configlet/pull/421#issuecomment-915274656

2021-09-08 15:07 UTC, ee7 commented
Something like that?

2021-09-09 06:38 UTC, ErikSchierboom commented
> I pushed a commit. The tracks see the same messages, but:
> 
> the text is in yellow rather than red
>the problems that we detect due to this PR don't by themselves cause configlet lint to exit non-zero.
> Is that what we want?

It is, thanks!

> I didn't do this part yet, but I can.

👍

2021-09-09 06:39 UTC, ErikSchierboom approved these changes

2021-09-10 11:12 UTC, ee7 commented
I felt the output was outrageously long, and so I've pushed some commits to compact the messages for these warnings.

I haven't done this with **errors** in the past - because errors will eventually be rare. But it seems sensible for these warnings during this transitional period.

See below for `configlet lint` output for `csharp`.

#### csharp now
```
The lint command is under development.
Please re-run this command regularly to see if your track passes the latest linting rules.

The following concepts exist in the `practices` array of a Practice Exercise in `../tracks/csharp/config.json`, but do not exist in the top-level `concepts` array
math-operators
linq
queues
extension-methods
stacks
multi-dimensional-arrays
streams
lazy-evaluation
recursion
yield
enumerables
generic-methods
lambdas
foreach
immutability
higher-order-functions
parallellism
comparing
generic-constraints
globalization
concurrency
big-integers
events

The following concepts exist in the `prerequisites` array of a Practice Exercise in `../tracks/csharp/config.json`, but are not in the `concepts` array of any user-facing Concept Exercise
math-operators
integers
bit-manipulation
enumerables
queues
stacks
multi-dimensional-arrays
streams
generic-methods
lambdas
extension-methods
foreach
immutability
higher-order-functions
parallellism
lazy-evaluation
comparing
generic-constraints
globalization
observables
big-integers
events

The following concepts exist in the `prerequisites` array of a Practice Exercise in `../tracks/csharp/config.json`, but do not exist in the top-level `concepts` array
math-operators
integers
enumerables
queues
stacks
multi-dimensional-arrays
streams
generic-methods
lambdas
extension-methods
foreach
immutability
higher-order-functions
parallellism
lazy-evaluation
comparing
generic-constraints
globalization
observables
big-integers
events

Basic linting finished successfully:
- config.json exists and is valid JSON
- config.json has these valid fields:
    language, slug, active, blurb, version, status, online_editor, key_features, tags
- Every concept has the required .md files
- Every concept has a valid links.json file
- Every concept has a valid .meta/config.json file
- Every concept exercise has the required .md files
- Every concept exercise has a valid .meta/config.json file
- Every practice exercise has the required .md files
- Every practice exercise has a valid .meta/config.json file
- Required track docs are present
- Required shared exercise docs are present

Configlet produced at least one warning - these will become errors in the future.
For more information, please see the documentation
https://github.com/exercism/docs/blob/main/building/configlet/lint.md
```


#### csharp before (9eb49e3e64f2b87b42cad3d09c324bf15e8763b2, same as the previously reviewed version)
```
The lint command is under development.
Please re-run this command regularly to see if your track passes the latest linting rules.

The Practice Exercise `leap` has `math-operators` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `high-scores` has `linq` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `hamming` has `linq` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `circular-buffer` has `queues` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `bob` has `extension-methods` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `matching-brackets` has `stacks` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `spiral-matrix` has `multi-dimensional-arrays` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `tournament` has `streams` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `dominoes` has `lazy-evaluation` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `forth` has `lazy-evaluation` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `grains` has `math-operators` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `collatz-conjecture` has `recursion` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `difference-of-squares` has `linq` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `difference-of-squares` has `math-operators` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `series` has `yield` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `sum-of-multiples` has `enumerables` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `accumulate` has `yield` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `accumulate` has `generic-methods` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `accumulate` has `lambdas` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `accumulate` has `extension-methods` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `accumulate` has `enumerables` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `accumulate` has `foreach` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `all-your-base` has `math-operators` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `largest-series-product` has `math-operators` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `pascals-triangle` has `yield` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `pascals-triangle` has `enumerables` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `pythagorean-triplet` has `generic-methods` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `rational-numbers` has `extension-methods` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `rational-numbers` has `immutability` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config.json

The Practice Exercise `rational-numbers` has `math-operators` in its `practices` array, which is not a `slug` in the top-level `concepts` array:
../tracks/csharp/config [...]

2021-09-10 11:23 UTC, ErikSchierboom commented
I like the abbreviated listing a lot.

> Now done. Did you want it to specify a date?

I'm thinking that a date might help trigger people a bit to actually do something with the warnings. Maybe mention end of October?

2021-09-10 15:53 UTC, ee7 commented on src/helpers.nim
> +var printedWarning* = false
This global is bad style. We should refactor it at some point, but it's okay for now.

2021-09-10 15:53 UTC, ee7 commented on src/lint/lint.nim
> +      These warnings will become errors in a future configlet release (at the end of October 2021).
We'll have to change this if we add more warnings that won't become errors at the same time.

2021-09-10 15:53 UTC, ee7 commented on src/lint/track_config.nim
> +proc checkConceptExercisePrerequisites(trackConfig: TrackConfig;
I'll change this to take a `seq[ConceptExercise]` parameter later.

2021-09-10 15:58 UTC, merged